// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BASE_MSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220325085530_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BASE_MSQL.Models.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Models")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 6,
                            Models = "Intel Core I5",
                            Name = "Processor",
                            Price = 5120m
                        },
                        new
                        {
                            Id = 2,
                            Count = 10,
                            Models = "Intel Core I7",
                            Name = "Processor",
                            Price = 9120m
                        },
                        new
                        {
                            Id = 3,
                            Count = 12,
                            Models = "Intel Core I8",
                            Name = "Processor",
                            Price = 11120m
                        },
                        new
                        {
                            Id = 4,
                            Count = 3,
                            Models = "Intel Core I9",
                            Name = "Processor",
                            Price = 13120m
                        },
                        new
                        {
                            Id = 5,
                            Count = 5,
                            Models = "AMD Ryzen 7",
                            Name = "Processor",
                            Price = 14134m
                        },
                        new
                        {
                            Id = 6,
                            Count = 61,
                            Models = "AMD Ryzen 5",
                            Name = "Processor",
                            Price = 10378m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
